name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - name: SAST
     run: |
        echo ${GITHUB_REF}
        echo ${GITHUB_ACTION_REPOSITORY}
        echo ${GITHUB_JOB}
        echo ${GITHUB_ACTIONS}
        echo ${GITHUB_EVENT_NAME}
        echo ${GITHUB_SHA}
        
        docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
