name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  SAST:
   runs-on: self-hosted
   container: 
    image: registry.fortidevsec.forticloud.com/fdevsec_sast:latest
   steps:
     - run: main 
     - run: hostname
