name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   
   - name: SAST
     run: |
        git init
        ls -al
        ls -al .github/
        echo "--------------"
        cat .git/HEAD
        git status
        docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.44 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
