name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   
   - name: SAST
     run: |
        ls -al
        ls -al .github
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        echo "GIT_WORK_TREE"
        echo "$GITHUB_WORKSPACE"
