name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v3
   - name: Hello world action step
     uses: ./ # Uses an action in the root directory
     id: hello
     with:
        who-to-greet: 'Mona the Octocat'
   - name: SAST
     run: |
       docker pull  registry.fortidevsec.forticloud.com/fdevsec_sast:latest
       docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest env
