name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v3

   - name: SAST
     run: |
       env >  env_file
       docker run --rm --env-file=env_file --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest main
