name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   container: registry.fortidevsec.forticloud.com/fdevsec_sast:latest
   steps:
     - run: ping fortidevsec.forticloud.com  -w 2
     - run: ping registry.fortidevsec.forticloud.com -w 2
