# This is a basic workflow that is manually triggered
name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: SAST
      run: docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.44 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
