name: FortiDevSec Scanner CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
   runs-on: self-hosted
   container: registry.fortidevsec.forticloud.com/fdevsec_sast:latest
   steps:
   - uses: actions/checkout@v2
   - name: SAST
     run: |
         env
         main
